blank_issues_enabled: true
contact_links:
  - name: Installation Help
    url: https://coramtix.dev/discord
    about: Please visit our Discord for help with your installation.
  - name: General Question
    url: https://coramtix.dev/discord
    about: Please visit our Discord for general questions about CoRamTix.
